### ISSUE TITLE
Auto-build wheels on pushes / merges

### ISSUE THREAD

**Issue by xileF1337** [phiweger/clonepool#16]
Via Github Actions, it should be easy to implement a basic continuous integration workflow that builds wheels of clonepool. This would allow the user to simply download clonepool in a single file without having to mess with the Git repo at all.

**Comment by phiweger** [comment]
@replikation is an expert on how to set this up ;)

**Comment by replikation** [comment]
TLDR:

create a new branch for testing.
inside clonepool main git-dir do `mkdir -p .github/workflows`
and `touch .github/workflows/wheelpush.yml`

wheelpush.yml
should/can look like this:

````yml
name: create_wheel

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: creat_a_whell
      run: pip blalba && python blabla
````

you add the commands behind `run:` to build and push you wheel 
you can create multiple commands:

````yml
 - name: step1
        run: |
           command 1
 - name: step 2
        run: |
           command2
````
